[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "aaa0af7338bfe9b89a688b9f45514ac54866bbef"
os = "macos"

    [[p7zip.download]]
    sha256 = "a9d424de3bef9920560f2eae224c78cdfccc79f01e9c1f331b312227ac6a6472"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.aarch64-apple-darwin.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "99f10e28778b7421ad0bf84d11ea82abcd134fa4"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "4293dc1e9ae87e87bc886bbd838cf9479743082d62d5bffc2c077db06847b3a5"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.aarch64-linux-gnu.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "2ff1124bc1ff451da8d41e0dd4633f3ed9125f80"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "067b1e0b552b9392f0097b8e69bce7d5f209f0b42b7a1537fbb66566f6db5f2e"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.aarch64-linux-musl.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "80047ddca404cddb5d96b7d96f2c8ca3c2eea527"
os = "freebsd"

    [[p7zip.download]]
    sha256 = "5e637f76fdd1b14902ecbb374707660bde94f3f938d20c7460008e9b5fde0b06"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.aarch64-unknown-freebsd.tar.gz"
[[p7zip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8a08a541fc0bece9a21c207eeea37a01c7538c5c"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "0fdf060c6b942e2bda5ad84db6126631ea4a024a0c21991f1b0debcfe8a818ea"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.armv6l-linux-gnueabihf.tar.gz"
[[p7zip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d50b144b827ee37a8f11d05d220cebac4ebeb0d9"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "001b3d6fe73a496ab826fda74a48609a760ac45e9829fc040b2886198105697d"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.armv6l-linux-musleabihf.tar.gz"
[[p7zip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "52e6fca8f0334fafae6d88752728a4094391d3cc"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "3a4e6256fc9461db5b8a09979ddb278a71a05159826138dd26d28d0a8de2958f"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.armv7l-linux-gnueabihf.tar.gz"
[[p7zip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b3871e26f83fe27970287686cbbf9c8a50d665d0"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "4068171ea8e3bcb1d3eddb845104757c01b5d7076574f63555a7a7c9cb5d92b6"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.armv7l-linux-musleabihf.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "f44de59216fca63e2d69083e90f0e6a1bbc3c397"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "2409b8b3fd7b9f60ada1cfba5ad087598b2493f6bf2eef8884c6826fdaa310b0"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.i686-linux-gnu.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "80deeb3f172b0de873ebf367a0549cdcc172e880"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "e12bf12206c2b0ab61166fb7071765b61531cf6504fd69bff1d8c508ffb6af13"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.i686-linux-musl.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "c65cfaaecd880f74df1b7a4fc87a52bed190cfed"
os = "windows"

    [[p7zip.download]]
    sha256 = "91b60b1b46e84fa21543624cb8bd27579a7ce49349ed5385a0ebb983483eaa81"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.i686-w64-mingw32.tar.gz"
[[p7zip]]
arch = "powerpc64le"
git-tree-sha1 = "eed7f71ca0bfacbea072453d3715f899f242ba06"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "7a25a8f32ec0fd87349262067a8025e4852b22e2fc0ee181f9c56129ed32dc02"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.powerpc64le-linux-gnu.tar.gz"
[[p7zip]]
arch = "riscv64"
git-tree-sha1 = "d98a46a71e489105d439e0c7acc4ee29f5b6fcca"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "2ddea399038f0bbc9ba5ba565108650a1abb15ec9f1fa081e66d03098044075d"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.riscv64-linux-gnu.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "4e34cf24f312bdf1a0cee74e947a25e4737f0185"
os = "macos"

    [[p7zip.download]]
    sha256 = "6efcd7adfe4535b17cd85b1009927d13598f211227387865d5390bca80062987"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.x86_64-apple-darwin.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "a6dea0ba1d26d38bdbf51c67816368f1cbd6c50d"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "3d6cadf4e76381b48313db4a9390a0956a38e4112aa0233500575db240af967e"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.x86_64-linux-gnu.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "d536123a7cd683acac649496750f37ba82f597a2"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "1d3f221f15d0ab1e450edee7559cf1a1e9e187e1af5c5190ee30096f171ff8d5"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.x86_64-linux-musl.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "71bc365a1bff4e1f736fb3580b3923e534d23afe"
os = "freebsd"

    [[p7zip.download]]
    sha256 = "529ea69ba47c7ca64d9f57778f732daeedd3ab4aa98e80e838531f14d50cc73e"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.x86_64-unknown-freebsd.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "8bd4a51cb90a61a30fb14dddc90b9a60549639a0"
os = "windows"

    [[p7zip.download]]
    sha256 = "6631b9edb954b0e5c95a179c05ba185ceb34ede7041f9823dab1b52b8a309bba"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.7.0+0/p7zip.v17.7.0.x86_64-w64-mingw32.tar.gz"
